services:
  - type: web
    name: firebed-app
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: AADE_USER_ID
        fromService:
          type: secret
          name: aade_user_id
      - key: AADE_SUBSCRIPTION_KEY
        fromService:
          type: secret
          name: aade_subscription_key
      - key: MYDATA_ENV
        value: sandbox
